# Combo II-DLD S75 / xc7s75fgga484-1.
# B6 is the 50 MHz main clock (trainer clock switch set to F).
# Pin mapping reuses week3's board 7-segment assignments; keypad and
# BDIO pins are from the Combo II-DLD S75 schematic.
set_property PACKAGE_PIN B6 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
create_clock -name clk -period 20.000 [get_ports clk]

# keys[11:0]: 0=key_1 1=key_2 2=key_3 3=key_4 4=key_5 5=key_6
#             6=key_7 7=key_8 8=key_9 9=key_0 10=key_star 11=key_sharp
set_property PACKAGE_PIN K4 [get_ports {keys[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[0]}]
set_property PACKAGE_PIN N8 [get_ports {keys[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[1]}]
set_property PACKAGE_PIN N4 [get_ports {keys[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[2]}]
set_property PACKAGE_PIN N1 [get_ports {keys[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[3]}]
set_property PACKAGE_PIN P6 [get_ports {keys[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[4]}]
set_property PACKAGE_PIN N6 [get_ports {keys[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[5]}]
set_property PACKAGE_PIN L5 [get_ports {keys[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[6]}]
set_property PACKAGE_PIN J2 [get_ports {keys[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[7]}]
set_property PACKAGE_PIN K2 [get_ports {keys[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[8]}]
set_property PACKAGE_PIN L1 [get_ports {keys[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[9]}]
set_property PACKAGE_PIN L7 [get_ports {keys[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[10]}]
set_property PACKAGE_PIN K6 [get_ports {keys[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[11]}]
set_false_path -from [get_ports {keys[*]}]

# BDIO0: 50 MHz / 2^N divided clock output. SLEW FAST / DRIVE 16 so the
# 50 MHz (N=0) edge looks reasonable on the trainer's BDIO header.
set_property PACKAGE_PIN F8 [get_ports {bdio0}]
set_property IOSTANDARD LVCMOS33 [get_ports {bdio0}]
set_property SLEW FAST [get_ports {bdio0}]
set_property DRIVE 16 [get_ports {bdio0}]

# BDIO2: UART TX, 9600 8N1.
set_property PACKAGE_PIN A7 [get_ports {bdio2}]
set_property IOSTANDARD LVCMOS33 [get_ports {bdio2}]

set_property PACKAGE_PIN H2 [get_ports {seg_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN J7 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN J3 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN J1 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN E4 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN E2 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN F5 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property PACKAGE_PIN F1 [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]

set_property PACKAGE_PIN K5 [get_ports {seg_com[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[0]}]
set_property PACKAGE_PIN K3 [get_ports {seg_com[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[1]}]
set_property PACKAGE_PIN K1 [get_ports {seg_com[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[2]}]
set_property PACKAGE_PIN L6 [get_ports {seg_com[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[3]}]
set_property PACKAGE_PIN G3 [get_ports {seg_com[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_com[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[5]}]
set_property PACKAGE_PIN H6 [get_ports {seg_com[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[6]}]
set_property PACKAGE_PIN H4 [get_ports {seg_com[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[7]}]
